services:
  - type: web
    name: apple-scraper
    env: python
    buildCommand: pip install flask gunicorn
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
