services:
  - type: web
    name: apple-scraper
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    plan: free
    region: singapore
    envVars:
      - key: TZ
        value: Asia/Taipei
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_SCRAPING
        value: true
      - key: SCRAPE_INTERVAL_MINUTES
        value: 5 